### ISSUE TITLE
NIST curves for ECDSA

### ISSUE THREAD

**Issue by blelump** [WebOfTrust/keri#15]
Hi,

the count codes table https://github.com/decentralized-identity/keri/blob/master/kids/kid0001.md#base64-master-code-table specifies only EDDSA and ECDSA via `secp256k1` curve. Android key storage and iOS Secure Enclave primary support for asymmetric encryption is RSA and ECDSA via NIST curves. Actually Android v13 will come with support for EDDSA, but the release is scheduled for Jul 2022, so the broader adoption will take years to make it useful. Furthermore Windows Helo comes only with support for RSA2048.

I suppose there's a reason NIST curves are not listed in the table. However usage of platform native TPM's is then not possible or at least would not be interoperable.

**Comment by SmithSamuelM** [comment]
The policy is to add codes when there is a demand or need, but not  to add codes well in advance of a need not to add codes in anticipation of needs.  So if there is a specific need for a code then indicate it specifically so we can add it. The new longer code tables can accomodate thousands of codes. Its the compact code tables that we want to be parsimonious with. If there is a marketing or regulatory "need" to show support or eventual support for codes then the suggestion is to put those in the bigger tables and reserve the compact tables for the high demand uses.

**Comment by blelump** [comment]
Got it. 

As the Android Key Store mechanism supports `ECDSA P-256` curve (same for iOS Secure Enclave), this one would be the desired to add to the table if anyone would like to use the platform based TPM's from these two companies.
